config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  mount Sidekiq::Web => "/sidekiq"

  resources :units
  resources :models
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "root#index"

  resources :rosters do
    resources :roster_models
  end

  resources :models do
    resources :units
  end

  namespace :import do
    resources :units, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :roster_model, optional: true

  has_many :units, dependent: :destroy

  enum category: {
    no_force_slot: 0,
    hq: 1,
    troop: 2,
    elite: 3,
    fast_attack: 4,
    heavy_support: 5,
    flyer: 6,
    transport: 7,
    lord_of_war: 8
  }

  def size_range
    return "#{min_size} - #{max_size}" if min_size != max_size
    max_size
  end
end

app/models/roster.rb
class Roster < ApplicationRecord
  FACTIONS = [
    "Ultramarines",
    "Iron Hands",
    "Imperial Fists"
  ].freeze

  belongs_to :user

  has_many :roster_models
end

app/models/roster_model.rb
class RosterModel < ApplicationRecord
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :model

  has_many :weapons, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rosters
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  belongs_to :unit
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: %i[ show edit update destroy ]

  # GET /models or /models.json
  def index
    @models = Model.all.order(category: :asc)
  end

  # GET /models/1 or /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models or /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to model_url(@model), notice: "Model was successfully created." }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1 or /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to model_url(@model), notice: "Model was successfully updated." }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1 or /models/1.json
  def destroy
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url, notice: "Model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def model_params
      params.fetch(:model, {})
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_with(model: model) do |form| %>
  <% if model.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
        <% model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/models/_model.html.erb
<div id="<%= dom_id model %>">
</div>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Show this model", @model %> |
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="row">
    <div class="col">
      <h1>Models</h1>
    </div>
  </div>

  <div id="models" class="row">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @models.each do |model| %>
        <div class="col">
          <div class="card bg-light">
            <h5 class="card-header"><%= model.name %></h5>

            <%= image_tag("intercessor.png", class: "card-img-top") %>

            <div class="card-body">
              <div class="card-title">
                <dl class="row">
                  <dt class="col-sm-6">Battlefield Role</dt>
                  <dd class="col-sm-6"><%= model.category.humanize %></dd>

                  <dt class="col-sm-6">Size</dt>
                  <dd class="col-sm-6"><%= model.size_range %></dd>
                </dl>
              </div>
              <div class="card-text">
                <%= link_to "View statline and composition", model_units_path(model) %>
              </div>
              <p class="card-text"><small class="text-muted"><%= model.created_at %></small></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <br />
  <div class="row">
    <div class="col">
      <%= link_to "New model", new_model_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render "form", model: @model %>

<br>

<div>
  <%= link_to "Back to models", models_path %>
</div>

app/views/models/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @model %>

<div>
  <%= link_to "Edit this model", edit_model_path(@model) %> |
  <%= link_to "Back to models", models_path %>

  <%= button_to "Destroy this model", @model, method: :delete %>
</div>