config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  mount Sidekiq::Web => "/sidekiq"

  resources :units
  resources :models
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "root#index"

  resources :rosters do
    resources :roster_models
  end

  resources :models do
    resources :units
  end

  namespace :import do
    resources :units, only: [:index, :create]
  end
end

app/models/roster.rb
class Roster < ApplicationRecord
  FACTIONS = [
    "Ultramarines",
    "Iron Hands",
    "Imperial Fists"
  ].freeze

  belongs_to :user

  has_many :roster_models
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_roster, only: %i[show edit update destroy]

  # GET /rosters or /rosters.json
  def index
    return @rosters = [] if current_user.nil?
    @rosters = current_user.rosters
  end

  # GET /rosters/1 or /rosters/1.json
  def show
  end

  # GET /rosters/new
  def new
    @roster = current_user.rosters.new
  end

  # GET /rosters/1/edit
  def edit
  end

  # POST /rosters or /rosters.json
  def create
    @roster = current_user.rosters.new(roster_params)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to roster_url(@roster), notice: "Roster was successfully created." }
        format.json { render :show, status: :created, location: @roster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1 or /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to roster_url(@roster), notice: "Roster was successfully updated." }
        format.json { render :show, status: :ok, location: @roster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1 or /rosters/1.json
  def destroy
    @roster.destroy

    respond_to do |format|
      format.html { redirect_to rosters_url, notice: "Roster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      @roster = current_user.rosters.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def roster_params
      params.fetch(:roster, {}).permit(:name, :faction)
    end
end

app/helpers/roster_helper.rb
module RosterHelper
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/views/rosters/_form.html.erb
<%= form_with(model: roster) do |form| %>
  <% if roster.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
        <% roster.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row g-3">
    <div class="mb3">
      <%= form.label :name, class: "col-sm-1 col-form-label" %>
      <div class="col-sm-5">
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="mb3">
      <%= form.label :faction, class: "col-sm-1 col-form-label" %>
      <div class="col-sm-5">
        <%= form.text_field :faction, class: "form-control" %>
      </div>
    </div>

    <div class="col-12">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/rosters/_roster.html.erb
<div id="<%= dom_id roster %>">
</div>

app/views/rosters/edit.html.erb
<div class="container">
  <h1>Editing roster</h1>

  <%= render "form", roster: @roster %>

  <br>

  <div>
    <%= link_to "Show this roster", @roster, class: "btn btn-info" %>
    <%= link_to "Back to rosters", rosters_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/rosters/index.html.erb
<div class="container">
  <h1>Roster list</h1>

  <div id="rosters">
    <table class="table table-hover">
      <thead>
        <tr>
          <td>Name</td>
          <td>Faction</td>
          <td></td>
        </tr>
      </thead>

      <tbody>
        <% @rosters.each do |roster| %>
          <tr>
            <td><%= roster.name %></td>
            <td><%= roster.faction %></td>
            <td><%= link_to "Show", roster %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to "New roster", new_roster_path, class: "btn btn-primary" %>
</div>

app/views/rosters/new.html.erb
<h1>New roster</h1>

<%= render "form", roster: @roster %>

<br>

<div>
  <%= link_to "Back to rosters", rosters_path, class: "btn btn-secondary" %>
</div>

app/views/rosters/show.html.erb
<div class="container">
  <h1><%= @roster.name %></h1>
  <h2><%= @roster.faction %></h2>

  <div class="row">
    <div class="accordion">
      <% Model.categories.each do |(category, index)| %>
        <div class="accordion-item">
          <h2 class="accordion-header" id="<%= "panelsStayOpen-#{index}" %>">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="<%= "#panelsStayOpen-collapse-#{index}" %>" aria-expanded="true" aria-controls="<%= "panelsStayOpen-collapse-#{index}" %>">
              <%= category.humanize.upcase %>
            </button>
          </h2>
          <div id="<%= "panelsStayOpen-collapse-#{index}" %>" class="accordion-collapse collapse" aria-labelledby="<%= "panelsStayOpen-#{index}" %>">
            <div class="accordion-body">
              <%= link_to "Add model", roster_roster_models_path(@roster) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <br />
  <div>
    <%= link_to "Edit this roster", edit_roster_path(@roster), class: "btn btn-warning" %>
    <%= link_to "Back to rosters", rosters_path, class: "btn btn-secondary" %>
    <%# button_to "Destroy this roster", @roster, method: :delete, class: "btn btn-danger" %>
  </div>
</div>