config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  mount Sidekiq::Web => "/sidekiq"

  resources :units
  resources :models
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "root#index"

  resources :rosters do
    resources :roster_models
  end

  resources :models do
    resources :units
  end

  namespace :import do
    resources :units, only: [:index, :create]
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :model

  has_many :weapons, dependent: :destroy
end

app/controllers/import/units_controller.rb
module Import
  class UnitsController < ApplicationController

    def index; end

    def create
      if params[:file].blank?
        flash[:warning] = "No file submitted."
        return redirect_to import_units_path
      end

      # TODO: Move file upload process to S3
      file_path = File.join(Rails.root, "tmp", "storage", "unit_data_#{Time.current.strftime('%Y%m%d%H%M%S')}")
      File.write(file_path, params[:file].read)

      ImportUnitsJob.perform_later(file_path)

      flash[:info] = "Successfully uploaded data for processing."
      redirect_to import_units_path
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_model, only: %i[ index ]
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = @model.units.map { |unit| UnitPresenter.new(unit) }
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    def set_model
      @model = Model.find(params[:model_id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.fetch(:unit, {})
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
</div>

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Show this unit", @unit %> |
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <div class="row">
    <h1><%= @model.name %></h1>
  </div>

  <div id="units" class="row">
    <% @units.each do |unit| %>
      <table class="table">
        <thead class="table-dark">
          <tr>
            <td>Name</td>
            <td>Points</td>
            <td>M"</td>
            <td>WS</td>
            <td>BS</td>
            <td>S</td>
            <td>T</td>
            <td>W</td>
            <td>A</td>
            <td>Ld</td>
            <td>Sv</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= unit.name %></td>
            <td><%= unit.points %></td>
            <td><%= unit.movement %></td>
            <td><%= unit.ws %></td>
            <td><%= unit.bs %></td>
            <td><%= unit.strength %></td>
            <td><%= unit.toughness %></td>
            <td><%= unit.wounds %></td>
            <td><%= unit.attacks %></td>
            <td><%= unit.leadership %></td>
            <td><%= unit.sv %></td>
          </tr>
        </tbody>
      </table>

      <table class="table table-sm" colspan="6">
        <thead>
          <tr>
            <td>Name</td>
            <td>Points</td>
            <td>Type</td>
            <td>Range</td>
            <td>S</td>
            <td>AP</td>
            <td>D</td>
            <td>Notes</td>
          </tr>
        </thead>
        <tbody>
          <% unit.weapons.each do |weapon| %>
            <tr>
              <td><%= weapon.name %></td>
              <td><%= weapon.points %></td>
              <td><%= weapon.type %></td>
              <td><%= weapon.range %></td>
              <td><%= weapon.strength %></td>
              <td><%= weapon.armor_penetration %></td>
              <td><%= weapon.damage %></td>
              <td><%= weapon.ability_notes %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <%# Statistics %>
  <div class="row">

  </div>
  <%= link_to "New unit", new_unit_path, class: "btn btn-primary" %>
  <%= link_to "Back", models_path, class: "btn btn-secondary" %>
</div>

app/views/units/new.html.erb
<h1>New unit</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @unit %>

  <div>
    <%= link_to "Edit this unit", edit_unit_path(@unit), class: "btn btn-warning" %>
    <%= link_to "Back to units", units_path, class: "btn btn-secondary" %>

    <%= button_to "Destroy this unit", @unit, method: :delete, class: "btn btn-danger" %>
  </div>
</div>